[package]
edition = "2021"
name = "profiles"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles"

[dependencies]
profiles = {git = "https://github.com/holochain-open-dev/profiles", rev = "704f7be", package = "hc_zome_profiles_coordinator"}
